###
POST http://localhost:3001/api/users
content-type: application/json

{
  "password":"password",
  "username":"root1",
  "name":"Emmet",
  "email":"root1@test.test"
}

###
GET http://localhost:3000/users
