###
POST http://localhost:3001/api/login
content-type: application/json

{
  "password":"password",
  "username":"root"
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
  "password":"password",
  "username":"root1"
}