###
POST http://localhost:3001/api/users
content-type: application/json

{
  "password":"password",
  "username":"testUser1",
  "name":"Emmet",
  "email":"testUser1@test.test"
}

###
POST http://localhost:3001/api/users
content-type: application/json

{
  "password":"password",
  "username":"root17",
  "name":"Emmet",
  "email":"notanemail"
}

###
GET http://localhost:3001/api/users/637d0fe4a683ab7ad70ab6e0


###
GET http://localhost:3001/api/users/
